### ISSUE TITLE
Query Error!

### ISSUE THREAD

**Issue by Dynamit44** [Cleverscript/ProductDiscount#1]
при подключении дает ошибку
Query Error: SELECT `ID` FROM `b_iblock_element` WHERE OR `ID` IN (189) AND `ACTIVE` = 'Y';[[1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OR `ID` IN (189) AND `ACTIVE` = 'Y'' at line 1]

**Comment by Cleverscript** [comment]
Спасибо за обратную связь, исправлено!
https://github.com/Cleverscript/ProductDiscount/commit/5ddb419bf63cf91d854629906784d66403b09c15

**Comment by Dynamit44** [comment]
отлично, все работает!
а, active_to для елемента тут получить нельзя, я так понял.

**Comment by Cleverscript** [comment]
> отлично, все работает! а, active_to для элемента тут получить нельзя, я так понял.

класс предназначался только для получения списка id товаров, которые присутствуют в правилах работы с корзиной в блоке действия. Все остальные данные вы можете получить имея id товара, или наследоваться от этого класса с переопределением метода getDiscounProducts под свои нужды

**Comment by Dynamit44** [comment]
понял уже. спасибо
